### ISSUE TITLE
some keyerror in console

### ISSUE THREAD

**Issue by BlankRain** [coslyk/moonplayer-plugins#1]
the moonplayer is really cool~
as cool as moon.
```
Traceback (most recent call last):
  File "~/.moonplayer/plugins/res_sohu_tv.py", line 44, in explore_cb
    data = json.loads(page)['data']
KeyError: 'data'
Traceback (most recent call last):
  File "~/.moonplayer/plugins/res_sohu_tv.py", line 44, in explore_cb
    data = json.loads(page)['data']
KeyError: 'data'
```

**Comment by andywanghui** [comment]
remove the plugins,that will be ok

**Comment by BlankRain** [comment]
I want to use the plugin
